### ISSUE TITLE
Are there any plans to move this awesome idea forward?

### ISSUE THREAD

**Issue by Andries-Smit** [mweststrate/mxgit#4]
The current custom widget repo's are polluted with sample projects. It good that they are public shared, however, it would be better so store them separately. 

Having an option to make a Team Server public(read) would be an alternative. 

Cheers, Andries

**Comment by mweststrate** [comment]
Hey Andries!

This project is indeed no longer maintained, I doubt it will still work with the latest Mx versions, but it might :). Readonly TS repositories can best be requested at the community team
