### ISSUE TITLE
Not compatible with nodejs 10.x LTS

### ISSUE THREAD

**Issue by tobyee** [mweststrate/mxgit#5]
## Issue Description
Error messages shows as follow when run `mxgit` command by **Node.js 10.x**. (Lower version works fine)
```
mxgit: using Mendix-App-xxx.mpr (project dir: ./)
mxgit: initializing SVN dummy repository...
fs.js:128
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:128:9)
    at Object.exists (fs.js:196:3)
    at Object.copySync (D:\fix\mxgit\node_modules\fs-extra\lib\copy.js:62:23)
    at initializeSvnDir (D:\fix\mxgit\mxgit.js:314:6)
    at next (D:\fix\mxgit\mxgit.js:685:4)
    at D:\fix\mxgit\mxgit.js:693:6
    at checkSvnDir (D:\fix\mxgit\mxgit.js:307:3)
    at next (D:\fix\mxgit\mxgit.js:685:4)
    at D:\fix\mxgit\mxgit.js:693:6
    at D:\fix\mxgit\mxgit.js:758:3
```
## Trouble Shoot
Node.js 10.x  API `fs.exits`  require a callback function otherwise it will throw an exception. The version of `fs-extra` depended by `mxgit` have a bug that should use `fs.existsSync` instead of `fs.exists` in method `fs.copySync`, see the this commit jprichardson/node-fs-extra@1a71665. So we need to upgrade module `fs-extra` from **0.8.1** to **0.13.0** at least to fixed the compatibility problem.

**Comment by mweststrate** [comment]
I am no longer using or maintaining this package. However if you want, I can give you maintainer and publish permissions on this package, so that it doesn't block you!

**Comment by Tobyee** [comment]
@mweststrate
Thank you for the reply. I knew that the repo was marked as unmaintained, anyway, it's still a great job to create this npm package unless we can find an official way to use Git as version control tool for Mendix project. And good news is that it still works fine with Mendix 7!

I am appreciate that if I can become a maintainer and continue to maintain it. As it works fine currently, I just need to fix the compatibility problem with latest version of Node.js.

**Comment by mweststrate** [comment]
Wow really cool it still works ootb! Didn't expect that!

I've send a collaboration invite. Please note that I need your `npm` username as well to be able to grant npm publish permissions.

**Comment by Tobyee** [comment]
Thanks, I've accepted the invite, my npm's username is `tobyee`.

**Comment by mweststrate** [comment]
Added! You should now be able to publish the update

**Comment by tobyee** [comment]
Thanks, I will be soon to publish mxgit@0.0.6 which will including changes below 
- Update **Version history**, add 0.0.6 notes and 0.0.5 notes (missed)
- Fix the compatitility with nodejs 10.x
